feat: Adds `add_to_cart` GA4 event
vtex-apps/google-tag-manager pull request #106
Opened 2023-02-08 19:14 UTC by lucasfp13

#### What is the purpose of this pull request?

This PR intends to add the `add_to_cart` GA4 event to be sent when `vtex:addToCart` is received.

[`add_to_cart` event](https://developers.google.com/analytics/devguides/collection/ga4/reference/events?hl=en&client_type=gtag#add_to_cart)|
-|
![Screen Shot 2023-02-08 at 16 09 23](https://user-images.githubusercontent.com/15722605/217628290-5a2275a3-eb0f-4e8b-9982-2475f916d1b1.png)|

#### Types of changes

* [ ] Bug fix (a non-breaking change which fixes an issue)
* [x] New feature (a non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Requires change to documentation, which has been updated accordingly.

2023-02-08 21:07 UTC, natanfernandes requested changes

2023-02-08 21:07 UTC, natanfernandes commented on react/modules/gaEvents.ts
> +    items: {
`items` must be a array according to [docs](https://developers.google.com/analytics/devguides/collection/ga4/reference/events?hl=en&client_type=gtag#add_to_cart_item)

2023-02-14 20:13 UTC, natanfernandes approved these changes

2023-02-14 20:31 UTC, filipewl reviewed
Nice job Feijó!

Left an important comment for us to discuss: handling multiple items in the event.

2023-02-14 20:31 UTC, filipewl commented on react/modules/gaEvents.ts
> +    items: [item],
Here we're retrieving only the first item of `items`, but there could be more than 1. 

I also thought there could only be 1, but after some research, I found out there are some cases where more products are added in the same event! 🤯 There's this ["Buy Together"](https://github.com/vtex-apps/recommendation-shelf#:~:text=recommendation%2Dshelf-,recommendation%2Dbuy%2Dtogether,-recommendation%2Drefresh) component that lets [multiple products to be added at once](https://github.com/vtex-apps/add-to-cart-button/blob/8b31f7189f567c5e088d1f7592a0b690abd69629/react/AddToCartButton.tsx#L207-L221).
![](https://user-images.githubusercontent.com/20840671/87463820-712bc580-c5e8-11ea-80f8-e773f3a61f7e.gif)

Can we update this function to deal with multiple items?

2023-02-14 20:31 UTC, filipewl commented on react/modules/gaEvents.ts
> +    value: formattedPrice,
Assuming there could be multiple items being added to the cart, as I mentioned in a previous comment, I'm assuming we need to update this `value` to be the sum of all the items' prices.

2023-02-14 20:31 UTC, filipewl commented on react/__tests__/index.test.tsx
> +        items: [cartItem as CartItem],
Assuming there could be multiple items being added to the cart, as I mentioned in a previous comment, could you increment this test to have 2 items? Just to be testing a more thorough case.

2023-02-15 21:03 UTC, filipewl commented on react/modules/gaEvents.ts
> +export function addToCart(eventData: PixelMessage['data']) {
I think we can get better type insurance here:
```diff
- export function addToCart(eventData: PixelMessage['data']) {
+ export function addToCart(eventData: AddToCartData) {
```

2023-02-15 22:37 UTC, filipewl approved these changes

2023-02-16 14:16 UTC, merged