GA Event Blocker
vtex-apps/google-tag-manager pull request #149
Opened 2024-03-22 18:33 UTC by diegoleone

#### What is the purpose of this pull request?

GA Events were being blocked on Add to Wish List because there was a null pointer exception, incase the sku is undefined. This generated a console error. 

Test:
https://list--italiaonline.myvtex.com/outsunny-orto-urbano-pensile-tavolo-porta-piante-con-fodera-in-tessuto-per-giardino-91x91x81cm-legno-90980/p

#### Types of changes

* [ ] Bug fix (a non-breaking change which fixes an issue)
* [ ] New feature (a non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Requires change to documentation, which has been updated accordingly.

2024-04-02 15:43 UTC, Mecrano requested changes

2024-04-03 08:28 UTC, diegoleone commented on react/modules/gaEvents.ts
> +  const variant = sku ? sku.itemId : product.items[0].sellers
Done.

2024-04-10 14:31 UTC, cdcs0128 requested changes
declare selectedItem types

2024-04-16 15:38 UTC, cdcs0128 approved these changes

2024-04-16 21:40 UTC, Mecrano approved these changes
LGTM

2024-04-16 21:42 UTC, merged