Add metadata information following the App Store standards
vtex-apps/google-tag-manager pull request #43
Opened 2020-12-17 13:50 UTC by alcentu

#### What is the purpose of this pull request?
Update the app's metadata following the new App Store standards, so we can read it properly when rendering the PDP. I haven't changed any code line.

#### What problem is this solving?
It will allow us to publish this app at the App Store. 

#### How should this be manually tested?
NA

#### Screenshots or example usage
NA

#### Types of changes

* [x] Bug fix (a non-breaking change which fixes an issue)
* [ ] New feature (a non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Requires change to documentation, which has been updated accordingly.

2020-12-17 18:32 UTC, klzns requested changes

2020-12-17 18:32 UTC, klzns commented on public/metadata/messages/en-US.json
> +      "Track events like 'product impression', 'product click', 'add to cart', 'checkout' and 'order placed' automatically"
```suggestion
      "Send all Google Enhanced Commerce events"
```

2020-12-17 18:32 UTC, klzns commented on public/metadata/messages/es-AR.json
> +      "Realice tracking de eventos como 'product impression', 'product click', 'add to cart', 'checkout' e 'order placed' automáticamente"
```suggestion
      "Envia todo los eventos de Google Enhanced Ecommerce"
```

2020-12-17 18:32 UTC, klzns commented on public/metadata/messages/pt-BR.json
> +      "Faça tracking de eventos como 'product impression', 'product click', 'add to cart', 'checkout' e 'order placed' automaticamente"
```suggestion
      "Envia todos os eventos do Google Enhanced Ecommerce"
```

2020-12-17 18:37 UTC, klzns approved these changes

2020-12-17 19:52 UTC, arturpimentel approved these changes

2020-12-18 17:20 UTC, klzns approved these changes

2020-12-18 17:20 UTC, merged