Adding allowHTML option
vtex-apps/google-tag-manager pull request #45
Opened 2020-12-22 19:50 UTC by lucis

Follow the discussion [here](https://vtex.slack.com/archives/C01B09QMHGT/p1608645277002400).

Related PR: [vtex/pixel-server]()

2020-12-22 19:56 UTC, gris approved these changes

2020-12-22 19:58 UTC, FabianaFerreira approved these changes

2020-12-22 21:19 UTC, klzns requested changes

2020-12-22 21:19 UTC, klzns commented on manifest.json
> +        "description": "Beware that using HTML tags can drastically impact the store's performance",
```suggestion
      "allowCustomHtmlTags": {
        "title": "Allow Custom HTML tags",
        "description": "Beware that using Custom HTML tags can drastically impact the store's performance",
```

2020-12-22 21:19 UTC, klzns commented on CHANGELOG.md
> +- `allowHTML` option on `settingsSchema`.
```suggestion
- `allowCustomHtmlTags ` option on `settingsSchema`.
```

2020-12-23 20:29 UTC, klzns approved these changes

2020-12-28 13:04 UTC, merged