Fix Refferer
vtex-apps/google-tag-manager pull request #70
Opened 2021-08-26 06:34 UTC by khrizzcristian

When the user moves to another page of the site, the referral is always empty. We added a variable in sessionStorage to keep the current url, when the user changes the page, if the initial referral is empty, takes the information from sessionStorage and then updates the variable.

#### How should this be manually tested?
[Workspace](https://longo--melimeloparis.myvtex.com/)

#### Screenshots or example usage
![Fix Refferer GTM Page View](https://user-images.githubusercontent.com/43498488/130912840-4325a943-fdf4-4de6-aced-d33f0a5fc543.jpg)

#### Types of changes

* [x] Bug fix (a non-breaking change which fixes an issue)
* [ ] New feature (a non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Requires change to documentation, which has been updated accordingly.

2021-09-01 12:18 UTC, igorbrasileiro approved these changes
Nice job 👏 ! I left a comment to improve readability, can you take a look?

2021-09-01 12:18 UTC, igorbrasileiro commented on react/modules/extraEvents.ts
> +        referrer: e.data.referrer ? e.data.referrer : sessionStorage.getItem('gtmRefferer') ? sessionStorage.getItem('gtmRefferer') : '',
What do you think about this suggestion?

```suggestion
        referrer: e.data.referrer ??  (sessionStorage.getItem('gtmRefferer') ?? ''),
```

2021-09-03 17:30 UTC, victorhmp approved these changes
LGTM! But please apply @igorbrasileiro's suggestion :)

2021-09-03 17:30 UTC, victorhmp commented on CHANGELOG.md
> +- Fix refferer
```suggestion
- `pageView` event's `referrer` property would always be empty after user navigation. 
```

2021-09-06 13:36 UTC, igorbrasileiro commented on react/modules/extraEvents.ts
> +        referrer: e.data.referrer ? e.data.referrer : sessionStorage.getItem('gtmRefferer') ? sessionStorage.getItem('gtmRefferer') : '',
I also suggest you call the sessionStorage inside a try/catch block because if the user blocks the storage use, the page may break.

2021-09-09 16:43 UTC, icazevedo requested changes
Hey @khrizzcristian, I don't think this is an issue. If you access your website with a referrer different from `undefined`, let's say, `google.com`, you can see the referral is preserved. 

This is intended by design: take a look at [this piece of code](https://github.com/vtex-apps/store/blob/master/react/components/PageViewPixel.tsx#L31) from the `vtex.store` app. From what I've read on the internet, this is the recommended behavior for non-SPA websites. It's basically trying to mimic the same behavior.

I was considering your proposal when I found [this official GA doc](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications#do_not_update_the_document_referrer): 

> Do not update the document referrer

> When you create a tracker object using the create command, the value of document.referrer is stored on the tracker's referrer field. In the context of a single page application that doesn't use full page loads, the referrer field will always stay the same.

> Despite this, it is not necessary to update the referrer field manually prior to sending pageview hits. Google Analytics is able to automatically determine the correct navigation path.

Because of this, I don't think we should accept your PR. Could you give more insights on why you were doing that?

2021-09-09 16:48 UTC, khrizzcristian commented
> Hey @khrizzcristian, I don't think this is an issue. If you access your website with a referrer different from `undefined`, let's say, `google.com`, you can see the referral is preserved.
> 
> This is intended by design: take a look at [this piece of code](https://github.com/vtex-apps/store/blob/master/react/components/PageViewPixel.tsx#L31) from the `vtex.store` app. From what I've read on the internet, this is the recommended behavior for non-SPA websites. It's basically trying to mimic the same behavior.
> 
> I was considering your proposal when I found [this official GA doc](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications#do_not_update_the_document_referrer):
> 
> > Do not update the document referrer
> 
> > When you create a tracker object using the create command, the value of document.referrer is stored on the tracker's referrer field. In the context of a single page application that doesn't use full page loads, the referrer field will always stay the same.
> 
> > Despite this, it is not necessary to update the referrer field manually prior to sending pageview hits. Google Analytics is able to automatically determine the correct navigation path.
> 
> Because of this, I don't think we should accept your PR. Could you give more insights on why you were doing that?

Hello. It's an issue because the refferer is undefined everytime you change the page. If you move from homepage any page the refferer is undefined

2021-09-09 16:55 UTC, icazevedo commented
> > Hey @khrizzcristian, I don't think this is an issue. If you access your website with a referrer different from `undefined`, let's say, `google.com`, you can see the referral is preserved.
> > This is intended by design: take a look at [this piece of code](https://github.com/vtex-apps/store/blob/master/react/components/PageViewPixel.tsx#L31) from the `vtex.store` app. From what I've read on the internet, this is the recommended behavior for non-SPA websites. It's basically trying to mimic the same behavior.
> > I was considering your proposal when I found [this official GA doc](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications#do_not_update_the_document_referrer):
> > > Do not update the document referrer
> > 
> > 
> > > When you create a tracker object using the create command, the value of document.referrer is stored on the tracker's referrer field. In the context of a single page application that doesn't use full page loads, the referrer field will always stay the same.
> > 
> > 
> > > Despite this, it is not necessary to update the referrer field manually prior to sending pageview hits. Google Analytics is able to automatically determine the correct navigation path.
> > 
> > 
> > Because of this, I don't think we should accept your PR. Could you give more insights on why you were doing that?
> 
> Hello. It's an issue because the refferer is undefined everytime you change the page. If you move from homepage any page the refferer is undefined

I don't think this is the actual behavior. As I said, if you join from a `google.com` link, the referrer is `google.com` and stays as `google.com` until the user navigates to checkout.

2021-09-09 16:59 UTC, khrizzcristian commented
> > > Hey @khrizzcristian, I don't think this is an issue. If you access your website with a referrer different from `undefined`, let's say, `google.com`, you can see the referral is preserved.
> > > This is intended by design: take a look at [this piece of code](https://github.com/vtex-apps/store/blob/master/react/components/PageViewPixel.tsx#L31) from the `vtex.store` app. From what I've read on the internet, this is the recommended behavior for non-SPA websites. It's basically trying to mimic the same behavior.
> > > I was considering your proposal when I found [this official GA doc](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications#do_not_update_the_document_referrer):
> > > > Do not update the document referrer
> > > 
> > > 
> > > > When you create a tracker object using the create command, the value of document.referrer is stored on the tracker's referrer field. In the context of a single page application that doesn't use full page loads, the referrer field will always stay the same.
> > > 
> > > 
> > > > Despite this, it is not necessary to update the referrer field manually prior to sending pageview hits. Google Analytics is able to automatically determine the correct navigation path.
> > > 
> > > 
> > > Because of this, I don't think we should accept your PR. Could you give more insights on why you were doing that?
> > 
> > 
> > Hello. It's an issue because the refferer is undefined everytime you change the page. If you move from homepage any page the refferer is undefined
> 
> I don't think this is the actual behavior. As I said, if you join from a `google.com` link, the referrer is `google.com` and stays as `google.com` until the user navigates to checkout.

This is the actual behavior. The refferer is set only on the first page. After that, is undefined.

2021-09-09 17:35 UTC, icazevedo commented
@khrizzcristian This is the behavior I'm seeing when accessing store theme via google

https://user-images.githubusercontent.com/8127610/132734774-3c370843-792a-4cb2-849c-eb8a44cbf475.mov

2021-09-28 20:42 UTC, igorbrasileiro commented
Interestingly, the navigation inside the store using the Link component is client-side like a SPA. So, for example:
1. If I type directly on my browser: `storetheme.vtex.com`;
2. if you check the referrer value, it will be `''`, and it's right because you come from nowhere;
3. Click on a product from a shelf;
4. If you recheck the referrer, it will be the same, `''`, because you don't navigate through the browser.

2021-10-06 07:37 UTC, alexdinca commented
> Hey @khrizzcristian, I don't think this is an issue. If you access your website with a referrer different from `undefined`, let's say, `google.com`, you can see the referral is preserved.
> 
> This is intended by design: take a look at [this piece of code](https://github.com/vtex-apps/store/blob/master/react/components/PageViewPixel.tsx#L31) from the `vtex.store` app. From what I've read on the internet, this is the recommended behavior for non-SPA websites. It's basically trying to mimic the same behavior.
> 
> I was considering your proposal when I found [this official GA doc](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications#do_not_update_the_document_referrer):
> 
> > Do not update the document referrer
> 
> > When you create a tracker object using the create command, the value of document.referrer is stored on the tracker's referrer field. In the context of a single page application that doesn't use full page loads, the referrer field will always stay the same.
> 
> > Despite this, it is not necessary to update the referrer field manually prior to sending pageview hits. Google Analytics is able to automatically determine the correct navigation path.
> 
> Because of this, I don't think we should accept your PR. Could you give more insights on why you were doing that?

Hey @icazevedo , we're doing this PR because our client melimeloparis marketing team requested this. They've looked at the reports of the traffic and they don't have the correct data.

"Because the page does not reload when browsing and loads dynamic content, we cannot identify the referrer correctly, because of this we need that variable sent to the referrer to be sent correctly so that we can "paste" the session and thus assign correctly traffic source"

Basically they want to track every page movement. I've added a video in which you can clearly notice that when I browse to a product page from the homepage, the referrer isn't the homepage.

Waiting for your feedback.

https://user-images.githubusercontent.com/7852982/136159946-3573ea35-9e90-4ea9-a807-009e3743e757.mp4

2021-10-19 20:11 UTC, closed without merging