Fix/analytics
vtex-apps/google-tag-manager pull request #84
Opened 2022-02-11 14:39 UTC by rcapeto

#### What is the purpose of this pull request?

Fix {{ecommerce}} variable firing, pass null to {{ecommerce}} before pass values again, like google recommend.

#### What problem is this solving?

Fix unnecessary values firing inside {{ecommerce}}

#### How should this be manually tested?

[Workspace](https://fixgtmv2--brmotorolanew.myvtex.com/)

#### Screenshots or example usage

-- no need

#### Types of changes

* [x] Bug fix (a non-breaking change which fixes an issue)
* [ ] New feature (a non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Requires change to documentation, which has been updated accordingly.

2022-02-11 15:33 UTC, rcapeto commented
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! 🤖
> 
> Please select which version do you want to release:
> 
> * [x]  Patch (backwards-compatible bug fixes)
> * [ ]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually 😞

2022-02-14 16:01 UTC, leeoxleeo approved these changes

2022-02-16 21:17 UTC, leeoxleeo approved these changes

2022-02-23 19:53 UTC, victorhmp requested changes
Please update the CHANGELOG

2022-02-25 17:04 UTC, victorhmp requested changes

2022-02-25 17:04 UTC, victorhmp commented on react/modules/updateEcommerce.ts
> +}
Please lint this file. We don't use `;`s

2022-02-25 17:04 UTC, victorhmp commented on react/modules/updateEcommerce.ts
> +   (eventIndex >= 0) && window.dataLayer.splice(eventIndex, 1);
Add and actual `if` here to make it more explicit

2022-02-25 17:04 UTC, victorhmp commented on react/modules/updateEcommerce.ts
> +      (ecommerceNullIndex >= 0) && window.dataLayer.splice(ecommerceNullIndex, 1);
Same here

2022-02-25 17:04 UTC, victorhmp commented on react/modules/updateEcommerce.ts
> +      push({ ecommerce: null });
```suggestion

      push({ ecommerce: null });
```

2022-02-25 17:05 UTC, victorhmp commented
Forgot to comment on it, but the tests are also failing, please take a look at them too :)

2022-04-04 18:50 UTC, victorhmp approved these changes
LGTM, but please apply the suggestion to fix the CHANGELOG

2022-04-04 18:50 UTC, victorhmp commented on CHANGELOG.md
> +
Remove the version number and date

```suggestion
## [Unreleased]

```

2022-04-04 19:17 UTC, merged